import { bindValue, trigger } from "cs2/api";
import mod from "mod.json";

export type ToolId = "None" | "AddNode" | "RemoveNode" | "Slope" | "Smooth" | "MoveNode" | "Arrange" | "Reverse" | "Roundabout" | "Undo" | "Intersect" | "Replace" | "Upgrades" | "Measure" | "Ramp" | "MatchHeight" | "Health" | "Bridge" | "Fillet" | "Split" | "Helix" | "Duplicate" | "Connect" | "Parallel";

export const panelOpen$ = bindValue<boolean>(mod.id, "PanelOpen", false);
export const activeTool$ = bindValue<ToolId>(mod.id, "ActiveTool", "None");
export const slopeProfile$ = bindValue<number>(mod.id, "SlopeProfile", 0);
export const connectMode$ = bindValue<number>(mod.id, "ConnectMode", 0);
export const parallelOffset$ = bindValue<number>(mod.id, "ParallelOffset", 16);
export const parallelHeight$ = bindValue<number>(mod.id, "ParallelHeight", 0);
export const parallelReverse$ = bindValue<boolean>(mod.id, "ParallelReverse", false);
export type Phase = "" | "PickSource" | "PickStart" | "PickEnd" | "Place" | "Review";
export const phase$ = bindValue<Phase>(mod.id, "Phase", "");
export const summary$ = bindValue<string>(mod.id, "Summary", "");
export const slopeEase$ = bindValue<number>(mod.id, "SlopeEase", 50);
export const slopeArch$ = bindValue<number>(mod.id, "SlopeArch", 0);
export const slopeStartOffset$ = bindValue<number>(mod.id, "SlopeStartOffset", 0);
export const slopeEndOffset$ = bindValue<number>(mod.id, "SlopeEndOffset", 0);
export const curveMode$ = bindValue<number>(mod.id, "CurveMode", 0);
export const curveStrength$ = bindValue<number>(mod.id, "CurveStrength", 100);
export const curveKeepEnds$ = bindValue<boolean>(mod.id, "CurveKeepEnds", true);
export const smoothStrength$ = bindValue<number>(mod.id, "SmoothStrength", 100);
export const smoothKeepEnds$ = bindValue<boolean>(mod.id, "SmoothKeepEnds", true);
export const smoothGrades$ = bindValue<boolean>(mod.id, "SmoothGrades", true);
export const smoothRelax$ = bindValue<number>(mod.id, "SmoothRelax", 0);
export const moveNudgeX$ = bindValue<number>(mod.id, "MoveNudgeX", 0);
export const moveNudgeZ$ = bindValue<number>(mod.id, "MoveNudgeZ", 0);
export const moveHeight$ = bindValue<number>(mod.id, "MoveHeight", 0);
export const arrangeMode$ = bindValue<number>(mod.id, "ArrangeMode", 0);
export const arrangeBulge$ = bindValue<number>(mod.id, "ArrangeBulge", 100);
export const roundaboutRadius$ = bindValue<number>(mod.id, "RoundaboutRadius", 24);
export const roundaboutClockwise$ = bindValue<boolean>(mod.id, "RoundaboutClockwise", false);
export const roundaboutCustomRing$ = bindValue<boolean>(mod.id, "RoundaboutCustomRing", false);
export const moveSnap$ = bindValue<number>(mod.id, "MoveSnap", 0);
export const moveGridSize$ = bindValue<number>(mod.id, "MoveGridSize", 8);
export const sourceName$ = bindValue<string>(mod.id, "SourceName", "");
export const replaceKeepUpgrades$ = bindValue<boolean>(mod.id, "ReplaceKeepUpgrades", true);
export const upgradesSwapSides$ = bindValue<boolean>(mod.id, "UpgradesSwapSides", false);
export const parallelSpacing$ = bindValue<number>(mod.id, "ParallelSpacing", 0);
export const parallelGap$ = bindValue<number>(mod.id, "ParallelGap", 0);
export const parallelWidths$ = bindValue<number>(mod.id, "ParallelWidths", 1);
export const parallelBothSides$ = bindValue<boolean>(mod.id, "ParallelBothSides", false);
export const rampRight$ = bindValue<boolean>(mod.id, "RampRight", true);
export const rampEntry$ = bindValue<boolean>(mod.id, "RampEntry", false);
export const rampFlip$ = bindValue<boolean>(mod.id, "RampFlip", false);
export const rampAngle$ = bindValue<number>(mod.id, "RampAngle", 15);
export const rampTurn$ = bindValue<number>(mod.id, "RampTurn", 0);
export const rampLength$ = bindValue<number>(mod.id, "RampLength", 120);
export const rampHeight$ = bindValue<number>(mod.id, "RampHeight", 6);
export const rampType$ = bindValue<string>(mod.id, "RampType", "");
export const matchHeight$ = bindValue<number>(mod.id, "MatchHeight", 0);
export const presetsAvailable$ = bindValue<boolean>(mod.id, "PresetsAvailable", false);
export const presetNames$ = bindValue<string>(mod.id, "PresetNames", "");
export const selectionAvailable$ = bindValue<boolean>(mod.id, "SelectionAvailable", false);
export const usingSelection$ = bindValue<boolean>(mod.id, "UsingSelection", false);
export const healthIssues$ = bindValue<string>(mod.id, "HealthIssues", "");
export const healthSelected$ = bindValue<number>(mod.id, "HealthSelected", -1);
export const healthMinLength$ = bindValue<number>(mod.id, "HealthMinLength", 3);
export const duplicateMode$ = bindValue<number>(mod.id, "DuplicateMode", 0);
export const duplicateAngle$ = bindValue<number>(mod.id, "DuplicateAngle", 0);
export const duplicateHasGroup$ = bindValue<boolean>(mod.id, "DuplicateHasGroup", false);
export const moveItAvailable$ = bindValue<boolean>(mod.id, "MoveItAvailable", false);
export const layouts$ = bindValue<string>(mod.id, "Layouts", "");
export const undoHistory$ = bindValue<string>(mod.id, "UndoHistory", "");
export const helixRadius$ = bindValue<number>(mod.id, "HelixRadius", 30);
export const helixTurns$ = bindValue<number>(mod.id, "HelixTurns", 1);
export const helixClimb$ = bindValue<number>(mod.id, "HelixClimb", 8);
export const helixClockwise$ = bindValue<boolean>(mod.id, "HelixClockwise", false);
export const helixStartAngle$ = bindValue<number>(mod.id, "HelixStartAngle", 0);
export const helixStartHeight$ = bindValue<number>(mod.id, "HelixStartHeight", 0);
export const helixType$ = bindValue<string>(mod.id, "HelixType", "");
export const parallelTaper$ = bindValue<number>(mod.id, "ParallelTaper", 0);
export const splitMode$ = bindValue<number>(mod.id, "SplitMode", 0);
export const splitParts$ = bindValue<number>(mod.id, "SplitParts", 2);
export const splitSpacing$ = bindValue<number>(mod.id, "SplitSpacing", 48);
export const simplifyTolerance$ = bindValue<number>(mod.id, "SimplifyTolerance", 0.5);
export const filletRadius$ = bindValue<number>(mod.id, "FilletRadius", 40);
export const bridgeMode$ = bindValue<number>(mod.id, "BridgeMode", 0);
export const bridgeHeight$ = bindValue<number>(mod.id, "BridgeHeight", 10);
export const bridgeClearance$ = bindValue<number>(mod.id, "BridgeClearance", 8);
export const connectRotation$ = bindValue<number>(mod.id, "ConnectRotation", 0);

export const togglePanel = () => trigger(mod.id, "TogglePanel");
export const selectTool = (tool: ToolId) => trigger(mod.id, "SelectTool", tool);
export const setSlopeProfile = (value: number) => trigger(mod.id, "SetSlopeProfile", value);
export const setConnectMode = (value: number) => trigger(mod.id, "SetConnectMode", value);
export const setParallelOffset = (value: number) => trigger(mod.id, "SetParallelOffset", value);
export const setParallelHeight = (value: number) => trigger(mod.id, "SetParallelHeight", value);
export const setParallelReverse = (value: boolean) => trigger(mod.id, "SetParallelReverse", value);
export const applyPreview = () => trigger(mod.id, "ApplyPreview");
export const cancelPreview = () => trigger(mod.id, "CancelPreview");
export const rotateConnect = (steps: number) => trigger(mod.id, "RotateConnect", steps);
export const setSlopeEase = (value: number) => trigger(mod.id, "SetSlopeEase", value);
export const setSlopeArch = (value: number) => trigger(mod.id, "SetSlopeArch", value);
export const setSlopeStartOffset = (value: number) => trigger(mod.id, "SetSlopeStartOffset", value);
export const setSlopeEndOffset = (value: number) => trigger(mod.id, "SetSlopeEndOffset", value);
export const setCurveMode = (value: number) => trigger(mod.id, "SetCurveMode", value);
export const setCurveStrength = (value: number) => trigger(mod.id, "SetCurveStrength", value);
export const setCurveKeepEnds = (value: boolean) => trigger(mod.id, "SetCurveKeepEnds", value);
export const setSmoothStrength = (value: number) => trigger(mod.id, "SetSmoothStrength", value);
export const setSmoothKeepEnds = (value: boolean) => trigger(mod.id, "SetSmoothKeepEnds", value);
export const setSmoothGrades = (value: boolean) => trigger(mod.id, "SetSmoothGrades", value);
export const setSmoothRelax = (value: number) => trigger(mod.id, "SetSmoothRelax", value);
export const setMoveNudgeX = (value: number) => trigger(mod.id, "SetMoveNudgeX", value);
export const setMoveNudgeZ = (value: number) => trigger(mod.id, "SetMoveNudgeZ", value);
export const setMoveHeight = (value: number) => trigger(mod.id, "SetMoveHeight", value);
export const setArrangeMode = (value: number) => trigger(mod.id, "SetArrangeMode", value);
export const setArrangeBulge = (value: number) => trigger(mod.id, "SetArrangeBulge", value);
export const setRoundaboutRadius = (value: number) => trigger(mod.id, "SetRoundaboutRadius", value);
export const setRoundaboutClockwise = (value: boolean) => trigger(mod.id, "SetRoundaboutClockwise", value);
export const setRoundaboutCustomRing = (value: boolean) => trigger(mod.id, "SetRoundaboutCustomRing", value);
export const setMoveSnap = (value: number) => trigger(mod.id, "SetMoveSnap", value);
export const setReplaceKeepUpgrades = (value: boolean) => trigger(mod.id, "SetReplaceKeepUpgrades", value);
export const setUpgradesSwapSides = (value: boolean) => trigger(mod.id, "SetUpgradesSwapSides", value);
export const setParallelSpacing = (value: number) => trigger(mod.id, "SetParallelSpacing", value);
export const setParallelGap = (value: number) => trigger(mod.id, "SetParallelGap", value);
export const setParallelWidths = (value: number) => trigger(mod.id, "SetParallelWidths", value);
export const setParallelBothSides = (value: boolean) => trigger(mod.id, "SetParallelBothSides", value);
export const setRampRight = (value: boolean) => trigger(mod.id, "SetRampRight", value);
export const setRampEntry = (value: boolean) => trigger(mod.id, "SetRampEntry", value);
export const setRampFlip = (value: boolean) => trigger(mod.id, "SetRampFlip", value);
export const setRampAngle = (value: number) => trigger(mod.id, "SetRampAngle", value);
export const setRampTurn = (value: number) => trigger(mod.id, "SetRampTurn", value);
export const setRampLength = (value: number) => trigger(mod.id, "SetRampLength", value);
export const setRampHeight = (value: number) => trigger(mod.id, "SetRampHeight", value);
export const pickRampType = () => trigger(mod.id, "PickRampType");
export const useRoadType = () => trigger(mod.id, "UseRoadType");
export const setMatchHeight = (value: number) => trigger(mod.id, "SetMatchHeight", value);
export const savePreset = () => trigger(mod.id, "SavePreset");
export const loadPreset = (index: number) => trigger(mod.id, "LoadPreset", index);
export const deletePreset = (index: number) => trigger(mod.id, "DeletePreset", index);
export const selectIssue = (index: number) => trigger(mod.id, "SelectIssue", index);
export const rescanHealth = () => trigger(mod.id, "RescanHealth");
export const setHealthMinLength = (value: number) => trigger(mod.id, "SetHealthMinLength", value);
export const setDuplicateMode = (value: number) => trigger(mod.id, "SetDuplicateMode", value);
export const setDuplicateAngle = (value: number) => trigger(mod.id, "SetDuplicateAngle", value);
export const duplicateUseSelection = () => trigger(mod.id, "DuplicateUseSelection");
export const saveLayout = () => trigger(mod.id, "SaveLayout");
export const loadLayout = (index: number) => trigger(mod.id, "LoadLayout", index);
export const deleteLayout = (index: number) => trigger(mod.id, "DeleteLayout", index);
export const rollBack = (steps: number) => trigger(mod.id, "RollBack", steps);
export const setHelixRadius = (value: number) => trigger(mod.id, "SetHelixRadius", value);
export const setHelixTurns = (value: number) => trigger(mod.id, "SetHelixTurns", value);
export const setHelixClimb = (value: number) => trigger(mod.id, "SetHelixClimb", value);
export const setHelixClockwise = (value: boolean) => trigger(mod.id, "SetHelixClockwise", value);
export const setHelixStartAngle = (value: number) => trigger(mod.id, "SetHelixStartAngle", value);
export const setHelixStartHeight = (value: number) => trigger(mod.id, "SetHelixStartHeight", value);
export const pickHelixType = () => trigger(mod.id, "PickHelixType");
export const helixUseRoadType = () => trigger(mod.id, "HelixUseRoadType");
export const setParallelTaper = (value: number) => trigger(mod.id, "SetParallelTaper", value);
export const setSplitMode = (value: number) => trigger(mod.id, "SetSplitMode", value);
export const setSplitParts = (value: number) => trigger(mod.id, "SetSplitParts", value);
export const setSplitSpacing = (value: number) => trigger(mod.id, "SetSplitSpacing", value);
export const setSimplifyTolerance = (value: number) => trigger(mod.id, "SetSimplifyTolerance", value);
export const setFilletRadius = (value: number) => trigger(mod.id, "SetFilletRadius", value);
export const setBridgeMode = (value: number) => trigger(mod.id, "SetBridgeMode", value);
export const setBridgeHeight = (value: number) => trigger(mod.id, "SetBridgeHeight", value);
export const setBridgeClearance = (value: number) => trigger(mod.id, "SetBridgeClearance", value);
export const useSelection = () => trigger(mod.id, "UseSelection");
export const pickSource = () => trigger(mod.id, "PickSource");
export const setMoveGridSize = (value: number) => trigger(mod.id, "SetMoveGridSize", value);

/** One line per type: kind ("Road", "Track", "Pathway"), prefab name, icon path, tab separated. */
export const roadTypes$ = bindValue<string>(mod.id, "RoadTypes", "");
/** Prefab name of the shared road type for new roads, or "" for each road's own type. */
export const buildType$ = bindValue<string>(mod.id, "BuildType", "");
export const setBuildType = (name: string) => trigger(mod.id, "SetBuildType", name);
