import { bindValue, trigger } from "cs2/api";
import mod from "mod.json";

export type ToolId = "None" | "AddNode" | "RemoveNode" | "Slope" | "Smooth" | "Connect" | "Parallel";

export const panelOpen$ = bindValue<boolean>(mod.id, "PanelOpen", false);
export const activeTool$ = bindValue<ToolId>(mod.id, "ActiveTool", "None");
export const slopeProfile$ = bindValue<number>(mod.id, "SlopeProfile", 0);
export const connectMode$ = bindValue<number>(mod.id, "ConnectMode", 0);
export const parallelOffset$ = bindValue<number>(mod.id, "ParallelOffset", 16);
export const parallelHeight$ = bindValue<number>(mod.id, "ParallelHeight", 0);
export const parallelReverse$ = bindValue<boolean>(mod.id, "ParallelReverse", false);
export type Phase = "" | "PickStart" | "PickEnd" | "Review";
export const phase$ = bindValue<Phase>(mod.id, "Phase", "");
export const summary$ = bindValue<string>(mod.id, "Summary", "");
export const slopeEase$ = bindValue<number>(mod.id, "SlopeEase", 50);
export const slopeArch$ = bindValue<number>(mod.id, "SlopeArch", 0);
export const slopeStartOffset$ = bindValue<number>(mod.id, "SlopeStartOffset", 0);
export const slopeEndOffset$ = bindValue<number>(mod.id, "SlopeEndOffset", 0);
export const curveMode$ = bindValue<number>(mod.id, "CurveMode", 0);
export const curveStrength$ = bindValue<number>(mod.id, "CurveStrength", 100);
export const curveKeepEnds$ = bindValue<boolean>(mod.id, "CurveKeepEnds", true);
export const smoothStrength$ = bindValue<number>(mod.id, "SmoothStrength", 100);
export const smoothKeepEnds$ = bindValue<boolean>(mod.id, "SmoothKeepEnds", true);
export const smoothGrades$ = bindValue<boolean>(mod.id, "SmoothGrades", true);
export const smoothRelax$ = bindValue<number>(mod.id, "SmoothRelax", 0);
export const connectRotation$ = bindValue<number>(mod.id, "ConnectRotation", 0);

export const togglePanel = () => trigger(mod.id, "TogglePanel");
export const selectTool = (tool: ToolId) => trigger(mod.id, "SelectTool", tool);
export const setSlopeProfile = (value: number) => trigger(mod.id, "SetSlopeProfile", value);
export const setConnectMode = (value: number) => trigger(mod.id, "SetConnectMode", value);
export const setParallelOffset = (value: number) => trigger(mod.id, "SetParallelOffset", value);
export const setParallelHeight = (value: number) => trigger(mod.id, "SetParallelHeight", value);
export const setParallelReverse = (value: boolean) => trigger(mod.id, "SetParallelReverse", value);
export const applyPreview = () => trigger(mod.id, "ApplyPreview");
export const cancelPreview = () => trigger(mod.id, "CancelPreview");
export const rotateConnect = (steps: number) => trigger(mod.id, "RotateConnect", steps);
export const setSlopeEase = (value: number) => trigger(mod.id, "SetSlopeEase", value);
export const setSlopeArch = (value: number) => trigger(mod.id, "SetSlopeArch", value);
export const setSlopeStartOffset = (value: number) => trigger(mod.id, "SetSlopeStartOffset", value);
export const setSlopeEndOffset = (value: number) => trigger(mod.id, "SetSlopeEndOffset", value);
export const setCurveMode = (value: number) => trigger(mod.id, "SetCurveMode", value);
export const setCurveStrength = (value: number) => trigger(mod.id, "SetCurveStrength", value);
export const setCurveKeepEnds = (value: boolean) => trigger(mod.id, "SetCurveKeepEnds", value);
export const setSmoothStrength = (value: number) => trigger(mod.id, "SetSmoothStrength", value);
export const setSmoothKeepEnds = (value: boolean) => trigger(mod.id, "SetSmoothKeepEnds", value);
export const setSmoothGrades = (value: boolean) => trigger(mod.id, "SetSmoothGrades", value);
export const setSmoothRelax = (value: number) => trigger(mod.id, "SetSmoothRelax", value);
